{{- if and .Values.components.controlApi .Values.persistence.enabled (not .Values.database.url) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelect-data
  labels:
    app: orchestrator-api
    {{- include "modelect.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
